"""Query the refs/ DBs across the core MS title-examination topics and
dump consolidated findings to scripts/research_findings.md for the SPEC."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from dotenv import load_dotenv

load_dotenv(ROOT / ".env")

from doc_embed import RefLibrary

TOPICS = [
    ("period_of_examination",        "period of title examination Mississippi marketable record title how far back"),
    ("mineral_severance",            "severance of minerals from surface estate reservation Mississippi"),
    ("mineral_fractional",           "fractional mineral interest reservation undivided fraction tracking"),
    ("after_acquired_title",         "after-acquired title doctrine warranty deed Mississippi estoppel"),
    ("tax_sales",                    "tax sale title redemption period two-year three-year void Mississippi"),
    ("adverse_possession",           "adverse possession Mississippi statute of limitations real property"),
    ("heirship",                     "heirship affidavit intestate succession descent and distribution Mississippi"),
    ("curative_statutes",            "curative statute 30-year marketable title act Mississippi"),
    ("chancery_partition",           "chancery court partition decree confirmation sale to pay debts"),
    ("deeds_of_trust",               "deed of trust release statute of limitations time-bar mortgage Mississippi"),
    ("cotenancy",                    "tenancy in common joint tenancy survivorship Mississippi cotenants"),
    ("legal_descriptions",           "legal description PLSS section township range Choctaw meridian Mississippi"),
    ("gaps_strangers",               "gap in chain of title wild deed stranger to title"),
    ("patents_sovereignty",          "patent sovereignty homestead United States land patent"),
    ("forms_of_conveyance",          "warranty deed quitclaim special warranty Mississippi differences"),
    ("estates_probate",              "estate probate administration vesting on death Mississippi"),
    ("ad_valorem_taxes",             "ad valorem property taxes assessment lien Mississippi tax receipts"),
    ("liens_judgments",              "judgment lien federal tax lien state tax lien registry Mississippi"),
    ("easements_rights_of_way",      "easement right of way servitude Mississippi appurtenant"),
    ("oil_gas_lease",                "oil and gas lease Mississippi habendum primary term"),
    ("timber_deeds",                 "timber deed conveyance of standing timber Mississippi"),
    ("life_estate",                  "life estate reservation remainderman Mississippi"),
    ("estoppel_by_deed",             "estoppel by deed warranty Mississippi covenants"),
    ("homestead",                    "homestead exemption joinder of spouse Mississippi conveyance"),
    ("less_and_except",              "less and except exception out of legal description"),
]


def main() -> int:
    lib = RefLibrary.load(ROOT / "refs")
    out = []
    out.append("# Research findings — Mississippi title examination\n")
    out.append("Generated by scripts/research.py against refs/.\n")
    for slug, query in TOPICS:
        out.append(f"\n## {slug}\n")
        out.append(f"_Query: {query}_\n")
        try:
            hits = lib.retrieve(query, k=4, rerank=True)
        except Exception as e:
            out.append(f"\nERROR: {type(e).__name__}: {e}\n")
            continue
        for h in hits:
            text = h.text.strip()
            if len(text) > 1400:
                text = text[:1400] + " ..."
            out.append(f"\n**{h.citation}** (score {h.score:.3f}, doc {h.doc})\n")
            out.append("\n" + text + "\n")

    target = ROOT / "scripts" / "research_findings.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target} ({target.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
